### ISSUE TITLE
missing file gridsearch_%s_25dB_%s.csv

### ISSUE THREAD

**Issue by MT9211** [RaiBP/vlc_thesis#2]
Error using readmatrix (line 171)
Unable to find or open
'./equalization_params/gridsearch_selm_25dB_4csk.csv'.
Check the path and filename or file permissions.

Error in get_equalization_parameters (line 11)
params_matrix = readmatrix(filepath);

Error in monte_carlo_simulation (line 127)
equalization_parameters = get_equalization_parameters(modulation_type, equalization_type);

get this error while running the code .

**Comment by RaiBP** [comment]
Closed by [114c448](https://github.com/RaiBP/vlc_thesis/commit/114c448a8c4a3ae27d5c66edeb25f08003dc3e7e).
